// @bat/shared — barrel export

// Version constant (auto-generated by scripts/sync-version.sh)
export { BAT_VERSION } from "./version.js";

// Metrics payload types
export type {
	CpuMetrics,
	DiskIoMetric,
	DiskMetric,
	FdMetrics,
	MemMetrics,
	MetricsPayload,
	NetMetric,
	PsiMetrics,
	SwapMetrics,
	TcpMetrics,
	SocketMetrics,
	UdpMetrics,
	SnmpMetrics,
	NetstatMetrics,
	SoftnetMetrics,
	ConntrackMetrics,
	TopProcess,
} from "./metrics.js";

// Identity payload types
export type {
	BlockDeviceDTO,
	HostRow,
	IdentityPayload,
	NetInterfaceDTO,
} from "./identity.js";

// Alert types and rules
export type {
	AlertRule,
	AlertSeverity,
	AlertState,
	HealthResponse,
	HealthStatus,
	LiveResponse,
} from "./alerts.js";
export {
	ALL_ALERT_RULES,
	getAlertRule,
	getAlertRuleLabel,
	SIGNAL_EXPANSION_ALERT_RULES,
	TIER1_ALERT_RULES,
	TIER2_ALERT_RULES,
	TIER3_ALERT_RULES,
} from "./alerts.js";

// Constants
export {
	ALERT_THRESHOLDS,
	AUTO_RESOLUTION_THRESHOLD_SECONDS,
	DEFAULT_PUBLIC_PORT_ALLOWLIST,
	INTERVALS,
	RETENTION,
	SIGNAL_EXPANSION_THRESHOLDS,
	TIER2_THRESHOLDS,
	TIER3_THRESHOLDS,
} from "./constants.js";

// API route types and constants
export type {
	AlertItem,
	AllowedPort,
	HostDetailItem,
	HostOverviewItem,
	HostStatus,
	HostTag,
	MaintenanceWindow,
	MetricsDataPoint,
	MetricsQueryResponse,
	MetricsResolution,
	SparklinePoint,
	TagItem,
} from "./api.js";
export {
	API_ROUTES,
	hashHostId,
	MAX_ALLOWED_PORTS_PER_HOST,
	MAX_TAGS_PER_HOST,
	TAG_COLOR_COUNT,
	TAG_NAME_REGEX,
} from "./api.js";

// Tier 2 payload types
export type {
	DetectedSoftware,
	DiscoveredWebsite,
	DiskDeepScanData,
	DockerContainer,
	DockerImagesInfo,
	DockerStatusData,
	FailedService,
	LargeFile,
	ListeningPort,
	SecurityPostureData,
	ServicePortsData,
	SoftwareCategory,
	SoftwareDiscoveryData,
	SystemdServicesData,
	Tier2Payload,
	Tier2Snapshot,
	TopDir,
	WebsiteDiscoveryData,
} from "./tier2.js";

// Event and webhook types
export type {
	EventIngestPayload,
	EventItem,
	EventRow,
	WebhookConfig,
	WebhookConfigRow,
} from "./events.js";
export {
	EVENT_BODY_MAX_BYTES,
	EVENT_RETENTION_DAYS,
	EVENT_TAG_MAX_LENGTH,
	EVENT_TAGS_MAX_COUNT,
	EVENT_TITLE_MAX_LENGTH,
} from "./events.js";

// Maintenance window utilities
export {
	isInMaintenanceWindow,
	isValidTimeHHMM,
	toUtcHHMM,
} from "./maintenance.js";
