// @bat/shared — barrel export

// Version constant (auto-generated by scripts/sync-version.sh)
export { BAT_VERSION } from "./version.js";

// Metrics payload types
export type {
	CpuMetrics,
	DiskIoMetric,
	DiskMetric,
	FdMetrics,
	MemMetrics,
	MetricsPayload,
	NetMetric,
	PsiMetrics,
	SwapMetrics,
	TcpMetrics,
	SocketMetrics,
	UdpMetrics,
	SnmpMetrics,
	NetstatMetrics,
	SoftnetMetrics,
	ConntrackMetrics,
} from "./metrics.js";

// Identity payload types
export type {
	BlockDeviceDTO,
	HostRow,
	IdentityPayload,
	NetInterfaceDTO,
} from "./identity.js";

// Alert types and rules
export type {
	AlertRule,
	AlertSeverity,
	AlertState,
	HealthResponse,
	HealthStatus,
} from "./alerts.js";
export {
	ALL_ALERT_RULES,
	getAlertRule,
	getAlertRuleLabel,
	SIGNAL_EXPANSION_ALERT_RULES,
	TIER1_ALERT_RULES,
	TIER2_ALERT_RULES,
	TIER3_ALERT_RULES,
} from "./alerts.js";

// Constants
export {
	ALERT_THRESHOLDS,
	AUTO_RESOLUTION_THRESHOLD_SECONDS,
	DEFAULT_PUBLIC_PORT_ALLOWLIST,
	INTERVALS,
	RETENTION,
	SIGNAL_EXPANSION_THRESHOLDS,
	TIER2_THRESHOLDS,
	TIER3_THRESHOLDS,
} from "./constants.js";

// API route types and constants
export type {
	AlertItem,
	HostDetailItem,
	HostOverviewItem,
	HostStatus,
	MetricsDataPoint,
	MetricsQueryResponse,
	MetricsResolution,
} from "./api.js";
export { API_ROUTES, hashHostId } from "./api.js";

// Tier 2 payload types
export type {
	DiskDeepScanData,
	DockerContainer,
	DockerImagesInfo,
	DockerStatusData,
	FailedService,
	LargeFile,
	ListeningPort,
	PackageUpdate,
	PackageUpdatesData,
	SecurityPostureData,
	ServicePortsData,
	SystemdServicesData,
	Tier2Payload,
	Tier2Snapshot,
	TopDir,
} from "./tier2.js";
