#!/usr/bin/env bash
# Sync version from root package.json to all packages and generated files.
# Usage: ./scripts/sync-version.sh
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

VERSION=$(jq -r '.version' package.json)
if [ -z "$VERSION" ] || [ "$VERSION" = "null" ]; then
  echo "ERROR: no version in root package.json" && exit 1
fi
echo "Syncing version: ${VERSION}"

# JS packages
for pkg in packages/shared packages/worker packages/dashboard; do
  jq --tab --arg v "$VERSION" '.version = $v' "$pkg/package.json" > "$pkg/package.json.tmp"
  mv "$pkg/package.json.tmp" "$pkg/package.json"
  echo "  ✔ $pkg/package.json → $VERSION"
done

# Generated TypeScript constant
cat > packages/shared/src/version.ts << EOF
// Auto-generated by scripts/sync-version.sh — do not edit manually
export const BAT_VERSION = "${VERSION}";
EOF
echo "  ✔ packages/shared/src/version.ts → $VERSION"

# Rust probe (Cargo.toml)
sd '^version = ".*"' "version = \"${VERSION}\"" probe/Cargo.toml
echo "  ✔ probe/Cargo.toml → $VERSION"

echo "Done. Run 'cd probe && cargo generate-lockfile' if probe version changed."
