/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env=production --include-runtime=false --strict-vars=false src/worker-configuration.d.ts` (hash: bd272d2e66d08b2564eb8b74fca30722)
interface __BaseEnv_Env {
	BAT_KV: KVNamespace;
	DB: D1Database;
	CONNECT_EDGE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	ENVIRONMENT: string;
	CONNECT_DEPLOYMENT_ID: string;
	BAT_WRITE_KEY: string;
	BAT_READ_KEY: string;
	CONNECT_COORDINATOR: DurableObjectNamespace<import("./entry").ConnectCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./entry");
		durableNamespaces: "ConnectCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				"ENVIRONMENT" | "CONNECT_DEPLOYMENT_ID" | "BAT_WRITE_KEY" | "BAT_READ_KEY"
			>
		> {}
}
